### ISSUE TITLE
Test build on Openshift fails on non prod environment

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#62]
When we override the `TARGET_REGISTRY` to push built containers to in `client/template.json` as in http://paste.fedoraproject.org/423836/14733348/, it still tries to push built image to `registry.centos.org`. This can be seen from the logs for test build.

``` console
==> Pulling tested image (172.30.69.93:5000/bamachrn-python/python:test)
2   Trying to pull repository 172.30.69.93:5000/bamachrn-python/python ... 
3   test: Pulling from 172.30.69.93:5000/bamachrn-python/python
4   3d8673bd162a: Already exists
5   97b032b57f03: Already exists
6   e2c5f4274b80: Already exists
7   885c218d9d80: Already exists
8   440fa7d2411b: Already exists
9   a7ed6fc727df: Already exists
10  cf497160153e: Already exists
11  6f5c02f96fa9: Already exists
12  d161327122ee: Already exists
13  9846ac8dc07d: Already exists
14  30fedacb3f53: Already exists
15  b875eb329f00: Already exists
16  f485dc67b8aa: Already exists
17  Digest: sha256:09927b8298f721688a65f3edf0b48d5f9d57f5ac994f367b087f4478eabfe9f4
18  Status: Downloaded newer image for 172.30.69.93:5000/bamachrn-python/python:test
19  ==> Checking if test script is getting success
20  exec: "--entrypoint": executable file not found in $PATH
21  docker: Error response from daemon: Container command not found or does not exist..
22  ==> Re-tagging tested image (172.30.69.93:5000/bamachrn-python/python:test -> registry.centos.org:5000/bamachrn/python:20160908065609)
23  ==> Pushing the image to registry (registry.centos.org:5000/bamachrn/python:20160908065609)
24  The push refers to a repository [registry.centos.org:5000/bamachrn/python]
25  unable to ping registry endpoint https://registry.centos.org:5000/v0/
26  v2 ping attempt failed with error: Get https://registry.centos.org:5000/v2/: http: server gave HTTP response to HTTPS client
27   v1 ping attempt failed with error: Get https://registry.centos.org:5000/v1/_ping: http: server gave HTTP response to HTTPS client
28  ==> Sending mail of failed status to bamachrn@gmail.com
29  ERROR:root:Failed to load PyYAML, will not parse YAML
30  Getting image details from test phase
31  Pushing notification details to master_tube
32  Traceback (most recent call last):
33    File "/tube_request/send_failed_notify_request.py", line 19, in <module>
34      bs = beanstalkc.Connection(host=beanstalk_host)
35    File "/tube_request/beanstalkc.py", line 62, in __init__
36      self.connect()
37    File "/tube_request/beanstalkc.py", line 74, in connect
38      SocketError.wrap(self._socket.connect, (self.host, self.port))
39    File "/tube_request/beanstalkc.py", line 46, in wrap
40      raise SocketError(err)
41  beanstalkc.SocketError: [Errno -2] Name or service not known
```

This issue can be reproduced in the allinone vagrant setup.

**Comment by rtnpro** [comment]
@bamachrn ^^

**Comment by kbsingh** [comment]
@rtnpro this looks like a name / dns error - what remote host is the beanstalk client connecting to ?

**Comment by bamachrn** [comment]
There is issue in FQDN in two places, we have nowhere hard coded registry to registry.centos.org, this is definitely coming from some hosts file. Another kbsingh rightly pointed out. May be hosts entry and actual machine IP is not matching.

**Comment by rtnpro** [comment]
It does not seem to be a name / dns error. And, definitely no problem with hosts entry.

```console
[vagrant@cccp ~]$ cat /etc/hosts
127.0.0.1   cccp localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.100.100 openshift
192.168.100.100 openshift
192.168.100.100 openshift
127.0.0.1 atomic-scan.vm.centos.org
192.168.100.100 openshift
192.168.100.100 openshift
127.0.0.1 atomic-scan.vm.centos.org
192.168.100.100 openshift
192.168.100.100 openshift
127.0.0.1 atomic-scan.vm.centos.org
192.168.100.100 openshift
192.168.100.100 openshift
127.0.0.1 atomic-scan.vm.centos.org
192.168.100.100 openshift
192.168.100.100 openshift
127.0.0.1 atomic-scan.vm.centos.org
[vagrant@cccp ~]$ ping openshift
PING openshift (192.168.100.100) 56(84) bytes of data.
64 bytes from openshift (192.168.100.100): icmp_seq=1 ttl=64 time=0.029 ms
64 bytes from openshift (192.168.100.100): icmp_seq=2 ttl=64 time=0.031 ms
64 bytes from openshift (192.168.100.100): icmp_seq=3 ttl=64 time=0.056 ms
```

There's no may be or may not be. All that is there is "this is it". I have checked our source code for hard coded values for ``registry.centos.org``, and I could not find a source for this issue.

@bamachrn , could you specify where there are issues in FQDN?

@bamachrn could you setup vagrant allinone at your end for debugging?

**Comment by rtnpro** [comment]
So, if we add an entry ``192.168.100.100 registry.centos.org``, it should fix the problem, for now. But, this does not seem to be the proper solution.
